model = "gpt-5.4"
model_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
personality = "pragmatic"

[sandbox_workspace_write]
network_access = true

[windows]
sandbox = "elevated"

[plugins."github@openai-curated"]
enabled = true

[plugins."vercel@openai-curated"]
enabled = true

[mcp]
remote_mcp_client_enabled = true

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=uhyqbkonzcpicmezsflg"